name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('rag/requirements.txt') }}-v1
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Cython
      run: python -m pip install Cython

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r rag/requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run pytest
      run: |
        pytest tests/
