name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Cache pytest artifacts
      uses: actions/cache@v2
      with:
        path: .pytest_cache
        key: ${{ runner.os }}-pytest-${{ hashFiles('**/test_*.py') }}-${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-pytest-${{ hashFiles('**/test_*.py') }}-
          ${{ runner.os }}-pytest-

    - name: Upgrade pip and Install Cython
      run: |
        python -m pip install --upgrade pip
        pip install Cython

    - name: Install dependencies
      run: pip install -r rag/requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run pytest
      run: pytest tests/test_rag/test_file_conversion_router/test_converters/test_md_converter.py
